### PR TITLE
Bugfix/e2e tests

### PR DESCRIPTION
**Pull request by stevenbister**
## 📝 Description

Fixes the failing tests in Playwright by making the locators more specific. For example a test was failing because using `name: "Courses"` as the locator was causing it to find anything that contained the word "Courses"

## ⛳️ Current behavior (updates)

- Tests are using unspecific locators

## 🚀 New behavior

- Increases the specificity of the test locators by either chaining `getByRole` methods or using the `exact: true` parameter.

### CODE REVIEW

**Review by mattwendzina — COMMENTED** [review]
Looks good mate. I've not run any of the e2e tests before, so pulled down to check I could get them all running okay. E-commerce all passed, however AH was failed on one of the tests.  Looks related to config/setup maybe rather than a legit fail. Here's the error logs I got:
```
🔶 Mock server running
/Users/matthewwendzina/Documents/open-study-college/osc-v2/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (/Users/matthewwendzina/Documents/open-study-college/osc-v2/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at Object.<anonymous> (/Users/matthewwendzina/Documents/open-study-college/osc-v2/packages/osc-academic-hub/build/index.js:831:36)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/matthewwendzina/Documents/open-study-college/osc-v2/node_modules/@remix-run/serve/dist/cli.js:42:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
Error: server closed unexpectedly
    at ChildProcess.onClose (/Users/matthewwendzina/Documents/open-study-college/osc-v2/node_modules/start-server-and-test/src/index.js:80:14)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! Lifecycle script `test:e2e` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: osc-academic-hub@0.0.0
npm ERR!   at location: /Users/matthewwendzina/Documents/open-study-college/osc-v2/packages/osc-academic-hub

 ———————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:e2e for project osc-academic-hub and 3 task(s) they depend on (4s)

    ✖    1/4 failed
    ✔    3/4 succeeded [3 read from cache]

   View structured, searchable error logs at https://nx.app/runs/V0n0NIGC7x
```

**Comment by stevenbister** [comment]
> Looks good mate. I've not run any of the e2e tests before, so pulled down to check I could get them all running okay. E-commerce all passed, however AH was failed on one of the tests. Looks related to config/setup maybe rather than a legit fail.

Ahh looks like you might be missing a secret 🤔 I'll send you my `.env` file. I did notice that there was an error in the port in the command for AH so I have updated that

**Comment by stevenbister** [comment]
(Oh, AH will probably fail in CI as we haven't deployed the osc-api yet)

**Review by mattwendzina — APPROVED** [review]
LGTM

**Pull request merged**
