### PR TITLE
Feature/video

### LINKED ISSUE #214: [S11.1]: Video
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

n/a

### Linked Tasks

- [ ] #215 
- [ ] #216

### LINKED ISSUE #215: Build Video Component
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/214

### Description

Package:
https://www.npmjs.com/package/react-player

- To support ONLY Vimeo and Youtube (No video upload i.e. MP4)
- Preloading / Lazyloading
- Override poster image (`fallback`)
- Pause on scroll out of view
(iframe api)

Add testing
E2E Integration

### LINKED ISSUE #216: Video make dynamic with sanity
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/214

### Description

n/a

### PR DESCRIPTION
**Pull request by stevenbister**
- Closes #214 
- Closes #215 
- Closes #216 

## 📝 Description

Adds a `<VideoPlayer>` component which is able to take a YouTube or Vimeo url and render the iframe. It is using [react-player](https://www.npmjs.com/package/react-player) under the hood and it setup to default to the "light" setting which means it won't load the iframe until you interact with the preview, unless it is set to autoplay.

Using an intersection observer the video will pause when over half of it is out of view. I've picked this as it seemed like the best medium, but it can be tweaked if anyone has strong feelings.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

Adds a `<VideoPlayer>` component to `osc-ui` and the modules to `osc-studio` / `osc-ecommerce`

## 📝 Additional Information

Includes an `iconPath` prop which temporarily solves a problem I outlined in #685; however if #685 get's merged first this can be removed because I don't like it

### CODE REVIEW

**Comment by mattwendzina** [comment]
Looks great mate 👌 
A couple of small things:
- Accessibility - Doesn't appear to be a violation, but an incomplete. Appears to be a contrast issue on the content text over the image. I guess it's hard because if it's there all the way through a video then contrast will be constantly changing. Maybe one option maybe is to give it a dark semi-transparent background to help give to make the contrast a bit more consistent?
- Tests:
- Final Test appears to be failing when I run it locally. The overlay div still has the 'is-hidden' classname which by the looks of it, it shouldn't. 
- Curious as to why you're mocking out fetch api. Don't see it being used but perhaps it is behind the scenes? Tests seem to run fine without it there.

**Review by mattwendzina — CHANGES_REQUESTED** [review]
Looks great mate 👌
A couple of small things:

Accessibility - Doesn't appear to be a violation, but an incomplete. Appears to be a contrast issue on the content text over the image. I guess it's hard because if it's there all the way through a video then contrast will be constantly changing. Maybe one option maybe is to give it a dark semi-transparent background to help give to make the contrast a bit more consistent?
Tests:
Final Test appears to be failing when I run it locally. The overlay div still has the 'is-hidden' classname which by the looks of it, it shouldn't.
Curious as to why you're mocking out fetch api. Don't see it being used but perhaps it is behind the scenes? Tests seem to run fine without it there.

**Comment by stevenbister** [comment]
Thanks man :)

> Accessibility - Doesn't appear to be a violation, but an incomplete. Appears to be a contrast issue on the content text over the image. I guess it's hard because if it's there all the way through a video then contrast will be constantly changing. Maybe one option maybe is to give it a dark semi-transparent background to help give to make the contrast a bit more consistent? 

It's already got a transparent overlay on it, I think like you said it's because Axe can't determine the background from the video. I've put in a fallback colour so if the image/video doesn't load for whatever reason the text will still be visible. But I think this might have to be one of those ones where the CMS user will have to make the decision on the video and just be aware to use videos with darker backgrounds when overlaying text.

> Tests: Final Test appears to be failing when I run it locally. The overlay div still has the 'is-hidden' classname which by the looks of it, it shouldn't. 

Aha! Yeah I changed how I wanted it to work and it looks like I forgot to update the test... Ooops!

> Curious as to why you're mocking out fetch api. Don't see it being used but perhaps it is behind the scenes? Tests seem to run fine without it there.

Yeah, `react-player` uses it in the background I think, so it's just there to keep it happy. I've added a more comment for context

**Review by mattwendzina — APPROVED** [review]
LGTM

**Review by hi-im-si — APPROVED** [review]

**Pull request merged**
