### PR TITLE
Feature/drawer component

### LINKED ISSUE #735: Drawer styling
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/733

### Description

n/a

### PR DESCRIPTION
**Pull request by stevenbister**
- Closes https://github.com/Open-Study-College/osc/issues/797
- Closes #735

## 📝 Description

Adds a drawer component. Given how different the styling and some of props needed to be, rather than having this as a variant of the `Modal` in #801 I decided it would be better off being it's own component.

Unlike the `Modal` this component will be mounted when the page loads, making use of Radix's `forceMount` prop. This is to allow us to get the `width` & `height` of the `DrawerContent` and assign them to css variables for use in transitioning it. Particularly vertically, where we can't know the height before content is added.

Because of this I have had to add an `!important` declaration to the `c-drawer__overlay` when it has a closed state. Radix applies an inline `pointer-events: auto` to it, meaning when the page loads we won't be able to click on anything. If we weren't using `forceMount` this wouldn't be an issue as the overlay wouldn't exist until we opened the drawer.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

- Adds a drawer component
- Adds `--lg` modifier to the `o-icon`
- Adds `--no-shadow` modifier to the `c-button`

### CODE REVIEW

**Review by mattwendzina — CHANGES_REQUESTED** [review]
Looks sweet mate 👌 

Just a few things:
- There appears to be an accessibility violation on the root:
`Focusable content should be disabled or be removed from the DOM`
For the Pinned Trigger:
- When you select an input on mobile it closes the Contact Form
- If you tab onto it there is no focus styling which would may be helpful?
- I think in mobile view, at least according to the designs, the contact form would have the pinned trigger on the top and presumably come up from the bottom. Maybe this functionality is already here but just isn't demonstrated in Storybook?
- Seems to be a bit of a weird bug/quirk that seems to be hard to reproduce - it just seems to happen randomly for me sometimes. Attached screen recording below.
Tests:
- Perhaps would be good to have some tests that test the opening and closing of the drawers?

Screen recording of bug:

https://user-images.githubusercontent.com/36510083/229115596-946199a0-87df-462c-b5ef-a25346ade1af.mov

**Comment by stevenbister** [comment]
Cool thanks man! That closing bug is a strange! Wonder what that's all about 😅 

> I think in mobile view, at least according to the designs, the contact form would have the pinned trigger on the top and presumably come up from the bottom. Maybe this functionality is already here but just isn't demonstrated in Storybook?

Yeah probably should add a story for that, but I was thinking of just swapping the direction on smaller screens with a media query or something. So the behaviour is there, just not demoed

**Comment by stevenbister** [comment]
@mattwendzina I think a lot of those issues were stemming from needing to `forceMount` the dialog content. That was mainly for the pinned variant, so I've tweaked it slightly so now, we add the trigger and close button to the drawer, position the close button outside the drawer hide the trigger when it renders. The markup for the pinned story feels a little clumsy now with having to duplicate the trigger but I think that's the best trade off.

**Comment by mattwendzina** [comment]
Hey mate, changes look good 👍 

I am still getting the quirky bug but it seems very random and I haven't found a consistent way to reproduce it 🤷‍♂️ Happy to just leave it for now and if we discover it being an issue when we implement into website we can address then? 

What were your thoughts on having focus styling for the pinned trigger?

I'd like to just be able to give it another demo on a mobile to check everything is working there now, but you have some conflicts so looks like that needs resolving before it deploys a branch.

https://user-images.githubusercontent.com/36510083/229710104-15f8447b-7d36-4ea4-8f4c-b51e4e781d9a.mov

**Comment by stevenbister** [comment]
Hmm you defo got the latest changes? I did add the focus styles if you tab onto the button 🤔 

image

I've rebased it now so try that, tbf for some reason the checks didn't run so perhaps something went a bit wonky

**Review by mattwendzina — APPROVED** [review]
Ah, yeah, appears I was on an older version! Seems to be working fine on desktop and mobile now and yep, can see the focused styling on the Pinner Trigger 🙌 

LGTM

**Comment by hi-im-si** [comment]
Looking slick, just a few niggles on mobile to iron out:

- On an iPhone 13 Pro Max, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but the button is now off screen.
image

- On an iPhone 13 Pro Max in landscape orientation, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but when i scroll down the content, the submit button and the text below it is cut off.

- On an iPhone 13 Pro Max in landscape orientation, when i click on the trigger on the [Custom Container](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--custom-container&viewMode=story) Variation, if the URL bar is visible the scroll is locked and i am unable to scroll the content in the drawer.
image

**Comment by stevenbister** [comment]
@hi-im-si Have (hopefully) updated those bugs

> On an iPhone 13 Pro Max, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but the button is now off screen.

I've added some state to grab the height of the button and set is as css custom property which we can use with calc to subtract from the `width: 100%` in those cases. Design has this change rotation on smaller screens but figured to include this as it might be useful later on

> On an iPhone 13 Pro Max in landscape orientation, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but when i scroll down the content, the submit button and the text below it is cut off.

Have added a new media query which will set the height of the drawer to 100% when it matches the height of the viewport which should allow for more consistent scrolling.

> On an iPhone 13 Pro Max in landscape orientation, when i click on the trigger on the [Custom Container](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--custom-container&viewMode=story) Variation, if the URL bar is visible the scroll is locked and i am unable to scroll the content in the drawer.

Same as above but I've also removed a rouge `max-height` on the inner content

**Comment by hi-im-si** [comment]
> @hi-im-si Have (hopefully) updated those bugs
> 
> > On an iPhone 13 Pro Max, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but the button is now off screen.
> 
> I've added some state to grab the height of the button and set is as css custom property which we can use with calc to subtract from the `width: 100%` in those cases. Design has this change rotation on smaller screens but figured to include this as it might be useful later on

LGTM 👍🏼

> 
> > On an iPhone 13 Pro Max in landscape orientation, when i click on the [pinned trigger](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--pinned-trigger&viewMode=story), the drawer slides out but when i scroll down the content, the submit button and the text below it is cut off.
> 
> Have added a new media query which will set the height of the drawer to 100% when it matches the height of the viewport which should allow for more consistent scrolling.
> 

Still seem to be getting the issue @stevenbister. Only in landscape mode. See video:
https://user-images.githubusercontent.com/1517907/231226494-6ba68fea-570d-48bc-8f16-bd7f36d3448c.mov
By adding a `100vh` to the drawer__content-inner seem to resolve the issue:
image


> > On an iPhone 13 Pro Max in landscape orientation, when i click on the trigger on the [Custom Container](https://62cd418bce39ee57e0c8cc30-tlbjsuytgq.chromatic.com/iframe.html?args=&id=osc-ui-dialogs-drawer--custom-container&viewMode=story) Variation, if the URL bar is visible the scroll is locked and i am unable to scroll the content in the drawer.
> 
> Same as above but I've also removed a rouge `max-height` on the inner content

Hmmm still getting the same issue. one for us to review in person i feel.

**Review by hi-im-si — CHANGES_REQUESTED** [review]
see follow-up responses

**Review by hi-im-si — APPROVED** [review]
Boom! LGTM

**Pull request merged**
