### PR TITLE
Refactor/modal

### PR DESCRIPTION
**Pull request by stevenbister**
- Closes https://github.com/Open-Study-College/osc/issues/734

## 📝 Description

Refactors the `Modal` component to make it more composable and set it up for the other drawer variations.

## ⛳️ Current behavior (updates)

- Modal it buildable via props, and restricted to those

## 🚀 New behavior

- Modal is composable and can take any kind of content
- Can be programatically controlled
- Adds styles / animations
- Can be swapped over to an `AlertDialog` which interrupts the user with important content and expects a response

### CODE REVIEW

**Comment by mattwendzina** [comment]
Looks great mate 👍 

Only issue I seem to be having is with the accessibility voice over for the title. When I turn voice over on in storybook and open the modals the only content that is read out for me is the description. For example, on the Primary story for Modal, it reads out the description: "An optional accessible description to be announced when the dialog is opened."
But it does not read out the title: "An accessible title to be announced when the dialog is opened."

**Review by mattwendzina — COMMENTED** [review]
Looks great mate 👍

Only issue I seem to be having is with the accessibility voice over for the title. When I turn voice over on in storybook and open the modals the only content that is read out for me is the description. For example, on the Primary story for Modal, it reads out the description: "An optional accessible description to be announced when the dialog is opened."
But it does not read out the title: "An accessible title to be announced when the dialog is opened."

**Comment by mattwendzina** [comment]
> > Looks great mate 👍
> > Only issue I seem to be having is with the accessibility voice over for the title. When I turn voice over on in storybook and open the modals the only content that is read out for me is the description. For example, on the Primary story for Modal, it reads out the description: "An optional accessible description to be announced when the dialog is opened." But it does not read out the title: "An accessible title to be announced when the dialog is opened."
> 
> Hmmmm, are you using Chrome by any chance? I think there might be a bug either in VoiceOver or in Chrome/FF 🤔 It will read both the title and description in Safari but you're right, only the description in Chrome/FF 😅

Yeah, the issue for me was in Chrome

**Comment by stevenbister** [comment]
Done a bit of digging and it looks like there's an open issue in Chrome which sounds like the same issue we've got here
- https://bugs.chromium.org/p/chromium/issues/detail?id=1404702&q=aria-labelledby&can=2

Given this and that the the title is handled by Radix not sure if there's much we can do here :/

**Review by mattwendzina — APPROVED** [review]
Based on fact that this bug is out of our hands, and posting issue/referencing the bug - LGTM 👍

**Review by hi-im-si — APPROVED** [review]

**Pull request merged**
