### PR TITLE
Feature/datatable

### LINKED ISSUE #276: [S21.1]: Data Table
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

N/A

### Linked Tasks

#277 
#1345

_No response_

### LINKED ISSUE #277: Build Data Table Component
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/276

### Description

Features to consider:
- [x] Sortable (Columns)
- [x] Filterable
- [x] Searchable
- [x] Support components inside cells
- [x] Pagination
- [ ] Drag n' Drop Columns/Rows (NICE TO HAVE)

### PR DESCRIPTION
**Pull request by stevenbister**
### 🧹 Please check off the following before submitting:

- [x] Close issues
- [x] Request reviewers
- [x] Assign yourself
- [ ] Add labels (e.g. `build:osc-ecommerce`)
- [x] Add project
- [x] Set project status
- [x] Add milestone

---

## ☑ List all github issues that this PR will close:

- Closes #276 
- Closes #277 

## 📝 Description

Adds a datatable component that uses https://tanstack.com/table/v8 and our `Table` component.
You should be able to search, sort, filter and paginate the data, all of which can be switched on or off globally and for the sort/filtering/search you will be able to enable/disabled them on the column level as well.

I've not implemented drag and drop in this case, as it's marked as a nice to have. But there are some examples in the docs on how to do it, so shouldn't be too tricky to add in the future.

I'm also unsure as to whether this might be better sat in the academic hub where we can have more customisation/control, especially with paginated data from the apis, but we'll see 😅

## ⛳️ Current behaviour (updates)

N/a

## 🚀 New behaviour

- Adds `Datatable` component

## 💣 Is this a breaking change (Yes/No): No

> Please describe any breaking changes.

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible cross-device impacts (iOS, Android)
- [ ] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

Columns will need to be generated with the `createColumnHelper` from `react-table` and setup follows the docs https://tanstack.com/table/v8/docs/guide/column-defs

### Summary by CodeRabbit

**New Features:**
- Added `DataTable` component with sorting, filtering, and pagination features.
- Enhanced `Table` component to accept additional custom props.
- Introduced new props in `DateRangePickerContainer` for custom behavior on date range changes or selection clearance.
- Added custom styling options to the `TextInput` component.

**Refactor:**
- Updated `invoices` and `students` data structures in `tableData.ts`.

**Style:**
- Improved visual appearance of the `DataTable` and `Table` components.

**Test:**
- Added test cases for the `DataTable` component.

**Chore:**
- Changed the title of the component from 'osc-ui/Table' to 'osc-ui/Tables/Table' in `Table.stories.tsx`.

### CODE REVIEW

**Review by mattwendzina — COMMENTED** [review]
Looks great mate!

Only thing I noticed is some dependency warnings in `DataTable.tsx`:

Screenshot 2023-09-04 at 14 22 38

**Comment by stevenbister** [comment]
> Only thing I noticed is some dependency warnings in `DataTable.tsx`:

Hmmm not getting that and the package is definitely installed. Did you defo run `npm run setup`? And if you did, did you try restarting your eslint server in vscode? Sometimes doesn't always update after an install

**Comment by mattwendzina** [comment]
> > Only thing I noticed is some dependency warnings in `DataTable.tsx`:
> 
> Hmmm not getting that and the package is definitely installed. Did you defo run `npm run setup`? And if you did, did you try restarting your eslint server in vscode? Sometimes doesn't always update after an install

Yeah, had another look and did a refresh. All is good 👍

**Review by mattwendzina — APPROVED** [review]
LGTM

**Comment by stevenbister** [comment]
> Yeah, had another look and did a refresh. All is good 👍

Phew! Ngl no idea what I wouldn't have done if that didn't work 😂

**Pull request merged**
