### PR TITLE
Feature/add icon picker to button

### PR DESCRIPTION
**Pull request by stevenbister**
## 📝 Description

While putting the demo page together I noticed that cms users can't add icons to the buttons so this PR aims to allow that.
This should help with setting up the Cards on the homepage which have icons on the quaternary button

## ⛳️ Current behavior (updates)

- Buttons can't have icons

## 🚀 New behavior

- Add icon picker to button module in studio
- Update ecommerce `<Button>` and `<Content>` components to take an icon prop and display the icon

### CODE REVIEW

**Comment by mattwendzina** [comment]
This LGTM. Did a test, tried different variants with the Icon and all good. 

My only slight issue is that there is no error validation for the Buttons inside the Content for the Type. Ie - I created a new button, but didn't set a type and the changes didn't pull through, I then noticed the an error on the button - see screenshot below. Fixed by selecting a type so not a big issue but not a great UX for the marketing team as they won't necessarily know what the problem is. 

My opinions aren't overly strong about it, or about it needing to be addressed now, I'm just flagging it to see what your view is. One option may be that a default is is set, in the same way that there is a default for the variant, but that's probably not ideal given that there isn't probably one standard type they will use. Anyway, be good to see what you think.

**Comment by stevenbister** [comment]
> This LGTM. Did a test, tried different variants with the Icon and all good.
> 
> My only slight issue is that there is no error validation for the Buttons inside the Content for the Type. Ie - I created a new button, but didn't set a type and the changes didn't pull through, I then noticed the an error on the button - see screenshot below. Fixed by selecting a type so not a big issue but not a great UX for the marketing team as they won't necessarily know what the problem is.
> 
> My opinions aren't overly strong about it, or about it needing to be addressed now, I'm just flagging it to see what your view is. One option may be that a default is is set, in the same way that there is a default for the variant, but that's probably not ideal given that there isn't probably one standard type they will use. Anyway, be good to see what you think.

Yeah good shout, should defo validate that bit!

**Comment by mattwendzina** [comment]
Screenshot 2023-03-15 at 10 46 18
Here's that screenshot = D

**Review by mattwendzina — APPROVED** [review]
LGTM!

**Pull request merged**
