### PR TITLE
chore: adds remix snippets to project settings

### PR DESCRIPTION
**Pull request by stevenbister**
## 📝 Description

Adds remix code snippets file to the `.vscode` folder in the root of the repo so we can all share the snippets.

## ⛳️ Current behavior (updates)

N/a

## 🚀 New behavior

Adds handful of remix snippets which you can access by typing "remix" into a typescript file in VsCode

image

### CODE REVIEW

**Comment by hi-im-si** [comment]
Might be worth looking at bringing across some from this repo?

https://github.com/atej/remix-snippets

**Review by hi-im-si — CHANGES_REQUESTED** [review]
See: https://github.com/Open-Study-College/osc/pull/446#issuecomment-1287427691

**Comment by stevenbister** [comment]
@hi-im-si updated :D

**Review by hi-im-si — APPROVED** [review]
🚀

**Pull request merged**
