### PR TITLE
Feature/add quinary text input variant

### PR DESCRIPTION
**Pull request by stevenbister**
### 🧹 Please check off the following before submitting:

- [ ] Close issues
- [x] Request reviewers
- [x] Assign yourself
- [ ] Add labels (e.g. `build:osc-ecommerce`)
- [ ] Add project
- [ ] Set project status
- [ ] Add milestone

---

## ☑ List all github issues that this PR will close:

N/a

## 📝 Description

Adds a another text input variant that will be used in the academic hub e.g.

image

image

## ⛳️ Current behaviour (updates)

N/a

## 🚀 New behaviour

- Adds `quinary` variant

## 💣 Is this a breaking change (Yes/No): No

> Please describe any breaking changes.

## 🧾 Final Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible cross-device impacts (iOS, Android)
- [x] I've considered possible cross-browser impacts (Chrome, Safari, Edge, Firefox)
- [ ] I've added tests to cover my changes (Unit, E2E, Integration, Contract, Functional, Acceptance etc)
- [ ] I've added or updated any documentation.

## 📝 Additional Information

> Any additional contextual information, such as relevant links/articles/documentation

### Summary by CodeRabbit

- New Feature: Introduced a new variant "quinary" for the TextInput component. This variant comes with a unique style and hides the label by default.
- Style: Updated CSS styles for the TextInput component to accommodate the new "quinary" variant, including changes to background color, border properties, and z-index adjustments.

### CODE REVIEW

**Review by jkellerman — APPROVED** [review]
LGTM!

**Comment by jkellerman** [comment]
Don't forget to add labels

**Comment by stevenbister** [comment]
> Don't forget to add labels

We don't need to build any apps off this so the labels aren't needed

**Comment by jkellerman** [comment]
> > Don't forget to add labels
> 
> We don't need to build any apps off this so the labels aren't needed

What about projects & milestones?

**Pull request merged**
